name: custom-vscode-server
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2

      - name: Install VSCode server
        run: npm install vscode-server

      - name: Launch VSCode server
        run: vscode-server start
